fix for #1927
monicahq/monica pull request #4511
Opened 2020-10-02 01:04 UTC by simonardejr

This is a quick fix for issue #[1927 ("Date you met" defaults to today upon edit, even if "I don't know" was selected previously)](https://github.com/monicahq/monica/issues/1927).

`$contact->first_met` doesn't exists, so, the condition is never met and the checkbox isn't checked. Also, `v-model` is always set to 'known' in `app.js`, making the last radio button checked by default.

2020-10-02 01:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/monicahq/monica?pullRequest=4511) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/monicahq/monica?pullRequest=4511) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/monicahq/monica?pullRequest=4511) it.</sub>

2020-10-05 19:38 UTC, asbiin requested changes
See my comments.
Please run `yarn prod` to build the assets too.

2020-10-05 19:38 UTC, asbiin commented on resources/views/people/introductions/edit.blade.php
> +                      @click="()=>{date_met_the_contact = 'unknown';}"
You may just write
```suggestion
                      @click="date_met_the_contact = 'unknown'"
```

2020-10-05 19:38 UTC, asbiin commented on resources/views/people/introductions/edit.blade.php
> +                      @click="()=>{date_met_the_contact = 'known';}"
You may just write
```suggestion
                      @click="date_met_the_contact = 'known'"
```

2020-10-05 23:33 UTC, simonardejr commented
Don't know if I've done everything right (fetching, merge, and stuff), but let me know if I need to do anything else :grin:

2020-10-09 18:23 UTC, asbiin commented
@simonardejr OK it *was* fine, but because of the merge of your other PR, this one needs to `git merge origin/master`, and run `yarn prod` again! (I know that's bothering...)

2020-10-09 22:34 UTC, simonardejr commented
I've done  the merging and re-run `yarn prod`, but the build didn't change any files... Don't know if what I've done was right, if not, just let me know and I don't mind to start another clean PR. (sorry for my bad english)

2020-10-15 08:34 UTC, merged

2020-10-15 08:35 UTC, asbiin commented
Thank you  @simonardejr

2020-10-15 10:39 UTC, simonardejr commented
:grin: :+1: