feat: add artisan command to create new account
monicahq/monica pull request #4745
Opened 2020-12-27 21:37 UTC by lpdyck

This adds an Account:Create command to artisan so that accounts can be created on an instance without opening public registration.

Resolves #4744 

## Checklist
### Before submitting the PR
- [x] Read the CONTRIBUTING document before submitting your PR.
- [x] If the PR is related to an issue or fix one, don't forget to indicate it.
- [x] Create your PR as draft if it is not final yet. Mark it as ready... when it’s ready. Otherwise the PR will be considered complete and rejected if it's not working.

### General checks
- [x] Make sure that the change you propose is the smallest possible.
- [x] The name of the PR should follow the [conventional commits guideline](https://github.com/monicahq/monica/blob/master/docs/contribute/readme.md#conventional-commits) that the project follows.

#### Other tasks
- [x] [CHANGELOG](https://github.com/monicahq/monica/blob/master/CHANGELOG.md) entry added, if necessary, under `UNRELEASED`.
- [x] [CONTRIBUTORS](https://github.com/monicahq/monica/blob/master/CONTRIBUTORS) entry added, if necessary.
- [x] If it's relevant and worth mentioning, create a changelog entry for this change. The changelog entry will appear inside the UI for all users to see. To know if your change is worth the creation of a changelog entry, [read the documentation](https://github.com/monicahq/monica/blob/master/docs/administrators/tips.md#when-is-it-relevant-to-create-a-changelog-entry).
- [ ] Don't forget to [ask for a free account](mailto:regis@monicahq.com) on https://monicahq.com as anyone who contributes can request a free account.

2020-12-27 21:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/monicahq/monica?pullRequest=4745) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/monicahq/monica?pullRequest=4745) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/monicahq/monica?pullRequest=4745) it.</sub>

2020-12-31 10:47 UTC, asbiin requested changes
Good idea! Thank you.
See my review

2020-12-31 10:47 UTC, asbiin commented on app/Console/Commands/CreateAccount.php
> +        Account::createDefault('John', 'Doe', $email, $password);
I would rather add real firstname/lastname than a default "John Doe" here.
They could be optional input.

2020-12-31 10:47 UTC, asbiin commented on app/Console/Commands/CreateAccount.php
> +class CreateAccount extends Command
Please add the `ConfirmableTrait` trait and a test like `$this->confirmToProceed()` (see [MigrateDatabaseCollation.php](https://github.com/monicahq/monica/blob/master/app/Console/Commands/MigrateDatabaseCollation.php) for instance)

2021-01-01 11:17 UTC, asbiin approved these changes
Great

2021-01-01 11:17 UTC, asbiin commented on app/Console/Commands/CreateAccount.php
> +    /**
```suggestion
    use ConfirmableTrait;
 
    /**
```

2021-01-01 15:39 UTC, djaiss commented
Good, thank you!

2021-01-03 04:35 UTC, lpdyck commented
I'm fairly certain the suddenly failing tests are coincidental to my adding a new test, but maybe I'm wrong?

2021-01-03 12:55 UTC, asbiin commented
@lpdyck no it's not. I'm trying to resolve it in #4763

2021-01-31 17:06 UTC, merged

2021-01-31 17:07 UTC, asbiin commented
Thank you @lpdyck !