feat: 4710 added ability to attach dates to gifts
monicahq/monica pull request #4909
Opened 2021-02-22 08:40 UTC by sktlmarat

Done:

- Added form to add the date (CreateGift.vue)
- Date is stored on the database (gift table)

Requires work:

- Display gift date on dashboard

2021-03-01 10:26 UTC, sktlmarat commented
Dear @asbiin,

Can I please get your feedback on this PR. I would really appreciate it.

Thanks!

2021-03-21 12:52 UTC, asbiin requested changes
That's great, see my comments.
I think we should also display the date on display mode (in `Gift.vue`)

2021-03-21 12:52 UTC, asbiin commented on resources/js/components/people/gifts/CreateGift.vue
> +          />
For dates we have a specific component:
```suggestion
          <form-date
            :id="'date'"
            v-model="newGift.date"
            :show-calendar-on-focus="true"
            :locale="locale"
            :class="[ dirltr ? 'fl dtc pr2' : 'fr dtc pr2' ]"
            :label="$t('people.gifts_add_date')"
            @submit="store"
          />
```

2021-03-21 13:03 UTC, asbiin commented
This close #4710

2021-03-21 14:04 UTC, sktlmarat commented
Hi @asbiin!
That's exactly what I meant by "Display gift date on dashboard".
Thank you for your feedback and addition! All changes were committed.

2021-03-21 17:26 UTC, asbiin approved these changes

2021-03-21 18:13 UTC, merged

2021-03-21 18:15 UTC, asbiin commented
thank you @sktlmarat !

2021-03-21 18:42 UTC, mgrhm commented
This is brilliant -- I just pulled it and I'm able to add dates to gifts I've given.

I'm not sure if I'm missing something, but is there an option to display the dates on the contact’s page?  As it stands, the date is correctly recorded but I can only see it when I click 'Edit'.

![Screen Shot 2021-03-21 at 18 41 01](https://user-images.githubusercontent.com/21129642/111916902-1ac72e80-8a75-11eb-8319-ccde32412066.png)