feat: add next reminder date to stayintouch
monicahq/monica pull request #5491
Opened 2021-09-08 13:50 UTC by MarkusDick

Fix #5158 

The screenshot of this feature:
<img width="1394" alt="next_reminder_stay_in_touch" src="https://user-images.githubusercontent.com/47363631/132521496-88390a5b-ca0a-4077-a207-3233775bb1fa.png">

I had to change the ContactController stayInTouch function because I needed the new calculated next reminder date when I update the frequency of the reminder.
Otherwise I'ld have needed to make a second request to the API.

### Checklist

#### Before submitting the PR
- [x] Read the [CONTRIBUTING document](https://github.com/monicahq/monica/blob/master/CONTRIBUTING.md) before submitting your PR.
- [x] If the PR is related to an issue or fix one, don't forget to indicate it.

### General checks
- [x] Make sure that the change you propose is the smallest possible.
- [x] The name of the PR should follow the [conventional commits guideline](https://github.com/monicahq/monica/blob/master/docs/contribute/readme.md#conventional-commits) that the project follows.

### Front-end changes
- [x] If you change the UI, make sure to ask repositories administrators first about your changes by pinging djaiss or asbiin in this PR. (pinged in issue)
- [x] Screenshots are included if the PR changes the UI.

2021-09-08 17:20 UTC, asbiin reviewed
I think adding the whole part "(next due ...)"  is quite long. Wouldn't be better to just add a tooltip-like when the mouse is over the text?

2021-09-08 17:30 UTC, MarkusDick commented
That's a great idea. I'll try it and update that PR. I'll convert it to draft.

2021-09-08 18:02 UTC, MarkusDick commented
Should the cursor be a pointer and the text "Stay in touch.." be underline dotted?

2021-09-08 19:40 UTC, mgrhm commented
> Should the cursor be a pointer and the text "Stay in touch.." be underline dotted?

Does a tool-tip work on mobile?  About half the time I use Monica, it's on my phone.  Almost all the times I want to check something quickly, it's using my phone.  (And is a tool-tip different than [using the `<abbr>` tag](https://github.com/monicahq/monica/issues/5158#issue-874506019)?)

Dotted underline is very common for the `<abbr>` tag, so many (most?) web users should know it means to hover on that for more information.

Not sure if this is possible, but my preference would be for an option to switch between the two.  Maybe make the tool-tip the default, but have an option to switch to the "(next due 08/09/2021)"?  While the full version is clumsier, it's more accessible.

2021-09-09 05:57 UTC, MarkusDick commented
> Does a tool-tip work on mobile?

Yes it does! :)

Here are screenshots:
Desktop:
<img width="1440" alt="tooltip-desktop" src="https://user-images.githubusercontent.com/47363631/132629898-3c798c64-d8a6-4f7b-a745-7e9ae84120b3.png">

Mobile:
![tooltip-mobile](https://user-images.githubusercontent.com/47363631/132630782-9329a7bf-57af-4491-b357-af3dabf5db1d.gif)

I'll push it in the evening. Are there any suggestions for improvement?

2021-09-09 06:43 UTC, mgrhm commented
Looks great, and glad it works on mobile!

Is there a trailing space at the end of “days” inside the tooltip tag? It looks like there might be on those screenshots.

The only other thing I’d do is stop it from [wrapping across lines](https://github.com/monicahq/monica/pull/5304). You can do that using the `nowrap-link` class.

2021-09-09 09:27 UTC, mgrhm commented
One other thought: since it’s a tooltip rather than inline, I’d prefer displaying the full date rather than the abbreviated three-letter month.

2021-09-09 11:04 UTC, MarkusDick commented
> I’d prefer displaying the full date rather than the abbreviated three-letter month.

Should it look like `09/23/2021` or `September 23, 2021`? @mgrhm 

> The only other thing I’d do is stop it from wrapping across lines. You can do that using the nowrap-link class.

> Is there a trailing space at the end of “days” inside the tooltip tag? It looks like there might be on those screenshots.

Both added / fixed. 👍

2021-09-09 11:19 UTC, mgrhm commented
> Should it look like 09/23/2021 or September 23, 2021?

I’d choose the latter. “September 23, 2021” is easier to read than “09/23/2021”.

2021-09-09 12:09 UTC, MarkusDick commented
I've added custom css for the dashed border because https://tachyons.io/docs/themes/borders/ is a lil bit buggy:


with the css classes `bb b--dashed` it looks like:
<img width="284" alt="buggy" src="https://user-images.githubusercontent.com/47363631/132681452-f484ce8b-2d42-4f34-919f-9d6def5b576f.png">

It's a known issue: https://github.com/tachyons-css/tachyons/issues/574

Now the finished look is:
Desktop:
![tooltip-desktop](https://user-images.githubusercontent.com/47363631/132681758-c9981b67-662a-4aa5-bc25-6c2b7dc75f19.gif)

Mobile:
<img height="400" src="https://user-images.githubusercontent.com/47363631/132681763-a001357d-a2e1-478a-8672-5ff2b51b5719.gif">

@asbiin Can u have a look at it? I don't know why the StyleCI is failing.

2021-09-11 08:50 UTC, asbiin commented
StyleCI is failing upstream, I'll fix it.

2021-09-12 20:40 UTC, asbiin requested changes
Great job! Thank you.

2021-09-12 20:40 UTC, asbiin commented on resources/js/components/people/StayInTouch.vue
> +      <span v-tooltip.bottom="$t('people.stay_in_touch_next_date', { date: formatDate(next_trigger_date)} )" class="bb dashed dib pointer nowrap-link">
consistency change
```suggestion
      <span v-tooltip.bottom="$t('people.stay_in_touch_next_date', { date: formatDate(next_trigger_date) })" class="bb dashed dib pointer nowrap-link">
```

2021-09-13 22:24 UTC, asbiin approved these changes

2021-09-13 22:24 UTC, merged

2021-09-13 22:25 UTC, asbiin commented
Thank you @MarkusDick