fix: misc bugfixes to reminders
monicahq/monica pull request #6931
Opened 2023-10-14 14:53 UTC by evanlihou

- Updating an existing reminder no longer deletes the user's notification channels
- Finishing the setup of a Telegram connection now triggers a scheduling of the user's notifications, making behavior consistent with how email verification works

It's been about 7 years since I've touched any code that uses Laravel, happy to make any updates you feel would improve the quality of this PR 🙂 

Fixes #6776

2023-10-14 14:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/monicahq/monica?pullRequest=6931) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/monicahq/monica?pullRequest=6931) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/monicahq/monica?pullRequest=6931) it.</sub>

2023-10-14 14:57 UTC, evanlihou commented on tests/Unit/Domains/Contact/ManageReminders/Services/UpdateContactReminderTest.php
> +        (new UpdateContactReminder())->execute($request);
I'm not entirely sure why, but in the context of the unit test, the old implementation would fail only if `UpdateContactReminder` was executed twice

2023-10-14 15:01 UTC, evanlihou commented
@djaiss @asbiin Thanks for all the work you do on this project! The issue that I opened for these bugs got closed, so I figured I'd try to implement a fix on my own.

The combination of these two issues made the experience of using Telegram reminders in Chandler very frustrating. Please review this small PR at your earliest convenience 🙂

2023-10-31 18:55 UTC, asbiin requested changes

2023-11-01 09:10 UTC, asbiin approved these changes

2023-11-01 09:11 UTC, merged