Enhance Robustness of RemoveViewedAtFromContacts Migration
monicahq/monica pull request #6963
Opened 2023-10-27 23:10 UTC by JensGryspeert

Issue #6960

2023-10-27 23:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/monicahq/monica?pullRequest=6963) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/monicahq/monica?pullRequest=6963) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/monicahq/monica?pullRequest=6963) it.</sub>

2023-10-28 12:39 UTC, asbiin requested changes
Thanks. See my comment

2023-10-28 12:39 UTC, asbiin commented on database/migrations/2017_01_28_222114_remove_viewed_at_from_contacts.php
>              );
If prefer to write it:
```suggestion
            if ($table->hasColumn('viewed_at')) {
                $table->dropColumn('viewed_at');
            }
```

2023-10-28 12:39 UTC, asbiin commented on database/migrations/2017_01_28_222114_remove_viewed_at_from_contacts.php
>              $table->dateTime('viewed_at')->nullable();
```suggestion
            if (!$table->hasColumn('viewed_at')) {
                $table->dateTime('viewed_at')->nullable();
            }
```

2023-10-28 21:30 UTC, JensGryspeert commented
> Thanks. See my comment

I squashed the modifications. The reason I work with early returns is to avoid if nesting in bigger code pages - to used at it haha sorry.

2023-10-28 21:35 UTC, asbiin approved these changes

2023-10-28 21:52 UTC, asbiin requested changes
I've missed this issue the first time ->

2023-10-28 21:52 UTC, asbiin commented on database/migrations/2017_01_28_222114_remove_viewed_at_from_contacts.php
>          });
Actually `Blueprint::hasColumn` does not exist, you have to write it:
```suggestion
        if (Schema::hasColumn('contacts', 'viewed_at')) {
            Schema::table('contacts', function (Blueprint $table) {
                $table->dropColumn('viewed_at');
            });
        }
```

2023-10-28 21:52 UTC, asbiin commented on database/migrations/2017_01_28_222114_remove_viewed_at_from_contacts.php
>          });
same:
```suggestion
        if (! Schema::hasColumn('contacts', 'viewed_at')) {
            Schema::table('contacts', function (Blueprint $table) {
                $table->dateTime('viewed_at')->nullable();
            });
        }
```

2023-10-31 09:51 UTC, merged