Increase storage
monicahq/monica pull request #7138
Opened 2024-01-30 10:05 UTC by Bhuvanasundari

How do I increase storage on Chandler beyond 50MB?

2024-01-30 10:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/monicahq/monica?pullRequest=7138) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/monicahq/monica?pullRequest=7138) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/monicahq/monica?pullRequest=7138) it.</sub>

2024-02-02 06:18 UTC, Bhuvanasundari commented
I increase the 50MB to 64MB changes occur in storage

2024-03-16 08:23 UTC, asbiin requested changes
Thank you, but I think this needs more work.

2024-03-16 08:23 UTC, asbiin commented on app/Domains/Settings/ManageStorage/Web/ViewHelpers/StorageIndexViewHelper.php
> +        $accountLimit = 64 * 1024 * 1024;
We don't want to change this, the accountLimit comes from this calculation

2024-03-16 08:23 UTC, asbiin commented on app/Helpers/StorageHelper.php
> +        $accountLimit = 64 * 1024 * 1024;
We don't want to change this, the accountLimit comes from this calculation

2024-03-16 12:39 UTC, djaiss commented
This is not something that we want.

If you need more storage, simply increase your ENV variable in your `.env` file.

The content of your env file should be 

```
DEFAULT_STORAGE_LIMIT=64
```

2024-03-16 12:39 UTC, closed without merging